using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TrashWebhooks.Properties
{
    internal class texts
    {
        public static string xxxxxxxxxxxxxxxxxxx2000char = @"x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x ".ToUpper().Replace(" ","\n");
        public static string niggernigggernigger2000char = @"nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger nigger".ToUpper().Replace(" ","\n");
        public static string trashwebhookıshere2000char = @"TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE TRASHWEBHOOKISHERE ".Replace(" ","\n");
        public static string nomorestealing2000char = "NO MORE STEALİNG ! \n NO MORE STEALİNG ! \n NO MORE STEALİNG ! \n NO MORE STEALİNG ! \n NO MORE STEALİNG ! \n NO MORE STEALİNG ! \n NO MORE STEALİNG ! \n NO MORE STEALİNG ! \n NO MORE STEALİNG ! \n NO MORE STEALİNG ! \n NO MORE STEALİNG ! \n NO MORE STEALİNG ! \n NO MORE STEALİNG ! \n NO MORE STEALİNG ! \n NO MORE STEALİNG ! \n NO MORE STEALİNG ! \n NO MORE STEALİNG ! \n NO MORE STEALİNG ! \n NO MORE STEALİNG ! \n NO MORE STEALİNG ! \n NO MORE STEALİNG ! \n NO MORE STEALİNG ! \n NO MORE STEALİNG ! \n NO MORE STEALİNG ! \n NO MORE STEALİNG ! \n NO MORE STEALİNG ! \n NO MORE STEALİNG ! \n NO MORE STEALİNG ! \n NO MORE STEALİNG ! \n NO MORE STEALİNG ! \n NO MORE STEALİNG ! \n NO MORE STEALİNG ! \n NO MORE STEALİNG ! \n NO MORE STEALİNG ! \n NO MORE STEALİNG ! \n NO MORE STEALİNG ! \n NO MORE STEALİNG ! \n NO MORE STEALİNG ! \n NO MORE STEALİNG ! \n NO MORE STEALİNG ! \n NO MORE STEALİNG ! \n NO MORE STEALİNG ! \n NO MORE STEALİNG ! \n NO MORE STEALİNG ! \n NO MORE STEALİNG ! \n NO MORE STEALİNG ! \n NO MORE STEALİNG ! \n NO MORE STEALİNG ! \n NO MORE STEALİNG ! \n NO MORE STEALİNG ! \n NO MORE STEALİNG ! \n NO MORE STEALİNG ! \n NO MORE STEALİNG ! \n NO MORE STEALİNG ! \n NO MORE STEALİNG ! \n NO MORE STEALİNG ! \n NO MORE STEALİNG ! \n NO MORE STEALİNG ! \n NO MORE STEALİNG ! \n NO MORE STEALİNG ! \n NO MORE STEALİNG ! \n NO MORE STEALİNG ! \n NO MORE STEALİNG ! \n NO MORE STEALİNG ! \n NO MORE STEALİNG ! \n NO MORE STEALİNG ! \n NO MORE STEALİNG ! \n NO MORE STEALİNG ! \n NO MORE STEALİNG ! \n NO MORE STEALİNG ! \n NO MORE STEALİNG ! \n NO MORE STEALİNG ! \n NO MORE STEALİNG ! \n NO MORE STEALİNG ! \n NO MORE STEALİNG ! \n NO MORE STEALİNG ! \n NO MORE STEALİNG ! \n NO MORE STEALİNG ! \n NO MORE STEALİNG ! \n NO MORE STEALİNG ! \n NO MORE STEALİNG ! \n NO MORE STEALİNG ! \n NO MORE STEALİNG ! \n NO MORE STEALİNG ! \n NO MORE STEALİNG ! \n NO MORE STEALİNG ! \n NO MORE STEALİNG ! \n NO MORE STEALİNG ! \n NO MORE STEALİNG ! \n NO MORE STEALİNG ! \n ";
    }
}
